contact-management-api:
    image: shethwala/contact-management-api
    container_name: contact-management-api
    mem_limit: 1073741824
    ports:
      - "8080:8080"
    environment:
      PROFILE: "aws-dev"
      SERVER_PORT: "8080"